apiVersion: v1
kind: Pod
metadata:
  name: webapp 
spec:
  containers:
    - name: event-simulator
      image: kodekloud/event-simulator
      env:
        - name: LOG_HANDLERS
          value: file
      volumeMounts:
        - mountPath: /log
          name: log-volume
      resources: 
  volumes:
    - name:  log-volume
      hostPath: 
       #directory location on host
       path: /var/log/webapp
       #this option is optional
       type: Directory